name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: go build cmd/main.go

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Unit Tests
        run: go test ./...

#      - name: Autograding
#        uses: education/autograding@v1
#        continue-on-error: true
#
#      - name: Github auto grader mark
#        uses: Romanow/google-sheet-autograder-marker@v1.0
#        with:
#          google_token: ${{secrets.GOOGLE_API_KEY}}
#          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
#          homework_number: 1
#          user_column: 'D'
#          column_offset: 'F'
#          mark: "'+"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy and wait
        uses: ashishkujoy/render-ci-deploy@v1.0.5
        with:
            service-id: ${{ secrets.RENDER_SERVICE_ID }}
            service-key: ${{ secrets.RENDER_SERVICE_KEY }}
            api-key: ${{ secrets.RENDER_API_KEY }}
            max-deployment-wait-ms: 360000
            delay-in-ms: 10000

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'